run:
  deadline: 5m
linters:
  enable:
    - bodyclose
    - gochecknoinits
    - gochecknoglobals
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - gosec
    - lll
    - misspell
    - nestif
    - testpackage
    - unparam
    - whitespace
    - wsl
    - revive
issues:
  include:
    - EXC0002
