name: Tests

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
  push:
    branches: [master]
    tags-ignore: ["**"]

env:
  GO_VERSION: "1.17"

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      -
        name: Pull dependencies
        run: make install-go-modules
      -
        name: Unit tests
        run: make test
      -
        name: Linter
        run: make lint
      -
        name: Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests

  test-windows:
    name: Unit Tests Windows
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      -
        name: Pull dependencies
        run: make install-go-modules
      -
        name: Unit tests
        run: make test
      -
        name: Linter
        run: make lint

  test-macos:
    name: Unit Tests macOS
    runs-on: macos-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      -
        name: Pull dependencies
        run: make install-go-modules
      -
        name: Unit tests
        run: make test
